Revert: Remove Assets/Plugins/Android/res folder
Unity 2021.3+ no longer supports placing Android resources directly
in Assets/Plugins/Android/res. This caused build failures.

Error: 'OBSOLETE - Providing Android resources in Assets/Plugins/Android/res was removed, please move your resources to an AAR or an Android Library'

Icon configuration needs to be done through Unity Editor Player Settings instead.